const Map<String, String> collegeLogos = {
  'Faculty of Engineering at Shoubra': 'BFES.jpeg',
  'Faculty of Engineering at Benha': 'BFOE.jpeg',
  'Faculty of Medicine': 'BFOM.jpeg',
  'Faculty of Commerce and Business Administration': 'FCOM.png',
  'Faculty of Law': 'FlAW.png',
  'Faculty of Pharmacy': 'BFOF.png',
  'Faculty of Agriculture': 'BFOA.jpeg',
  'Faculty of Education': 'FEDU.png',
  'Faculty of Arts': 'FART.png',
  'Faculty of Computers and Information': 'FCI.png',
  'Faculty of Science': 'BFOS.jpeg',
  'Faculty of Applied Arts': 'FAPA.png',
  'Faculty of Special Education': 'BFSE.jpeg',
  'Faculty of Physical Education': 'FPED.jpg',
  'Faculty of Veterinary Medicine': 'FVTM.jpg',
  'Faculty of Nursing': 'FNUR.jpg',
  'Faculty of Physiotherapy': 'BFPT.jpeg',
};
