// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAROFtoqMLr2avckTjnoJ-d5DPV8kFJ5mo',
    appId: '1:473450864452:web:bc5a529ba30f9879ba4111',
    messagingSenderId: '473450864452',
    projectId: 'sbu-lib-fc415',
    authDomain: 'sbu-lib-fc415.firebaseapp.com',
    storageBucket: 'sbu-lib-fc415.appspot.com',
    measurementId: 'G-GCWFWS26MJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlBZaR1I96Bsr8EZ8Z8LpKikaJJXUTUbE',
    appId: '1:473450864452:android:a62e68c00b6f4138ba4111',
    messagingSenderId: '473450864452',
    projectId: 'sbu-lib-fc415',
    storageBucket: 'sbu-lib-fc415.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHMGgUOZY0I2rkjT0jywYc9ykaM6GgiXA',
    appId: '1:473450864452:ios:3a7a4efa4359383aba4111',
    messagingSenderId: '473450864452',
    projectId: 'sbu-lib-fc415',
    storageBucket: 'sbu-lib-fc415.appspot.com',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHMGgUOZY0I2rkjT0jywYc9ykaM6GgiXA',
    appId: '1:473450864452:ios:3a7a4efa4359383aba4111',
    messagingSenderId: '473450864452',
    projectId: 'sbu-lib-fc415',
    storageBucket: 'sbu-lib-fc415.appspot.com',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAROFtoqMLr2avckTjnoJ-d5DPV8kFJ5mo',
    appId: '1:473450864452:web:aa170657bab5155fba4111',
    messagingSenderId: '473450864452',
    projectId: 'sbu-lib-fc415',
    authDomain: 'sbu-lib-fc415.firebaseapp.com',
    storageBucket: 'sbu-lib-fc415.appspot.com',
    measurementId: 'G-XZL6H8RFWC',
  );
}
